from selenium import webdriver  #toll that lets us instruct the behavior of the webdriver

options = webdriver.ChromeOptions()
options.add_argument(
    "disable-infobars"
)  #Makes it so that extra info naturally generated by web won't confuse the cursor
options.add_argument(
    "start-maximized"
)  #Makes it so that if a website changes items based on size it won't affect us
options.add_argument(
    "disbale-dev-shm-usage"
)  #avoids issues related to accessing web on a linux machinee(Repl is a linux machine)
options.add_argument(
    "no-sandbox"
)  #Adds more privilages to our scraper that are blocked by the internets sandboxing
options.add_experimental_option("excludeSwitches", ["enable-automation"])

driver = webdriver.Chrome()  #every web browser has a diffrent web driver
